CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `langID` int(2) NOT NULL DEFAULT 0, 
  `alias` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `UserID` varchar(30) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `OwnerID` varchar(30) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `hidden` tinyint(1) NOT NULL DEFAULT '4',
  `timeCreated` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `timeSaved` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `categoryID` int(11) NOT NULL,
  `extraCategoryID` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `code` varchar(255) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `description` longtext NOT NULL,
  `metaTitle` varchar(255) NOT NULL,
  `metaDescription` mediumtext NOT NULL,
  `metaKeywords` longtext NOT NULL,
  `icon` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`),
  KEY `hidden` (`hidden`),
  KEY `categoryID` (`categoryID`),
  KEY `extraCategoryID` (`extraCategoryID`),
  KEY `name` (`name`),
  KEY `langID` (`langID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;